FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app
COPY ./noava/noava.sln . 
COPY ./noava/noava ./noava
RUN dotnet restore
RUN dotnet tool install --global dotnet-ef --version 8.0.0
ENV PATH="$PATH:/root/.dotnet/tools"

