import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

//   // But you can create a sidebar manually

//   // tutorialSidebar: [
//   //   'intro',
//   //   'hello',
//   //   {
//   //     type: 'category',
//   //     label: 'Tutorial',
//   //     items: ['tutorial-basics/create-a-document'],
//   //   },
//   // ],
// };

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      customProps: { icon: 'getting started' },
      items: [
        'getting-started/create-account',
        'getting-started/create-deck',
        'getting-started/add-flashcard',
        'getting-started/share-deck-class',
        'getting-started/start-review',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      customProps: { icon: 'core concepts' },
      items: [
        'core-concepts/deck',
        'core-concepts/classroom',
        'core-concepts/study-modes',
        'core-concepts/scheduling',
        'core-concepts/progress-tracking',
        'core-concepts/mastery',
      ],
    },
    {
      type: 'category',
      label: 'Decks',
      customProps: { icon: 'decks' },
      items: ['decks/importing-cards', 'decks/reviews'],
    },
  ],
};

export default sidebars;
// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
