// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using noava.Data;

#nullable disable

namespace noava.Migrations
{
    [DbContext(typeof(NoavaDbContext))]
    [Migration("20260126161111_AddNotifications")]
    partial class AddNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("noava.Models.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("noava.Models.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FaqKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FAQs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Noava is a modern platform that helps you manage your business efficiently with cutting-edge technology and user-friendly interfaces.",
                            FaqKey = "what_is_noava",
                            Question = "What is Noava?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Simply sign up, configure your preferences, and start using our intuitive dashboard to manage all your operations in one place.",
                            FaqKey = "how_does_it_work",
                            Question = "How does it work?"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "We offer flexible pricing plans starting from €9.99 per month. Visit our pricing page for detailed information about features included in each plan.",
                            FaqKey = "what_are_the_costs",
                            Question = "What are the costs?"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "Yes, you can cancel your subscription at any time without any penalties or hidden fees. Your data will remain accessible for 30 days after cancellation.",
                            FaqKey = "can_i_cancel_anytime",
                            Question = "Can I cancel anytime?"
                        },
                        new
                        {
                            Id = 5,
                            Answer = "Absolutely. We use industry-standard encryption, regular security audits, and comply with GDPR regulations to ensure your data is always protected.",
                            FaqKey = "is_my_data_secure",
                            Question = "Is my data secure?"
                        },
                        new
                        {
                            Id = 6,
                            Answer = "We offer 24/7 email support, live chat during business hours, and comprehensive documentation. Premium plans include priority support and dedicated account managers.",
                            FaqKey = "support_options_available",
                            Question = "What support options are available?"
                        },
                        new
                        {
                            Id = 7,
                            Answer = "Yes, Noava integrates with popular tools like Slack, Google Workspace, Microsoft 365, and many others through our API and pre-built connectors.",
                            FaqKey = "integration_with_other_tools",
                            Question = "Can I integrate with other tools?"
                        },
                        new
                        {
                            Id = 8,
                            Answer = "Yes, we offer a 14-day free trial with full access to all features. No credit card required to start your trial.",
                            FaqKey = "free_trial",
                            Question = "Do you offer a free trial?"
                        });
                });

            modelBuilder.Entity("noava.Models.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("text");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("noava.Models.NotificationAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LabelKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("NotificationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.ToTable("NotificationActions");
                });

            modelBuilder.Entity("noava.Models.User", b =>
                {
                    b.Property<string>("ClerkId")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClerkId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("noava.Models.Notification", b =>
                {
                    b.HasOne("noava.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("noava.Models.NotificationAction", b =>
                {
                    b.HasOne("noava.Models.Notification", "Notification")
                        .WithMany("Actions")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("noava.Models.Notification", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("noava.Models.User", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
