// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using noava.Data;

#nullable disable

namespace noava.Migrations
{
    [DbContext(typeof(NoavaDbContext))]
    partial class NoavaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("noava.Models.Deck", b =>
                {
                    b.Property<int>("DeckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeckId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("DeckId");

                    b.ToTable("Decks");

                    b.HasData(
                        new
                        {
                            DeckId = 1,
                            CreatedAt = new DateTime(2026, 1, 22, 10, 15, 21, 865, DateTimeKind.Utc).AddTicks(5928),
                            Description = "Franse woorden voor beginners",
                            Language = "Frans",
                            Title = "Frans Woordenschat",
                            UpdatedAt = new DateTime(2026, 1, 22, 10, 15, 21, 865, DateTimeKind.Utc).AddTicks(5929),
                            Visibility = 0
                        },
                        new
                        {
                            DeckId = 2,
                            CreatedAt = new DateTime(2026, 1, 22, 10, 15, 21, 865, DateTimeKind.Utc).AddTicks(5931),
                            Description = "Engelse grammatica oefeningen",
                            Language = "Engels",
                            Title = "Engels Grammatica",
                            UpdatedAt = new DateTime(2026, 1, 22, 10, 15, 21, 865, DateTimeKind.Utc).AddTicks(5931),
                            Visibility = 2
                        },
                        new
                        {
                            DeckId = 3,
                            CreatedAt = new DateTime(2026, 1, 22, 10, 15, 21, 865, DateTimeKind.Utc).AddTicks(5933),
                            Description = "Spaanse zinnen voor dagelijks gebruik",
                            Language = "Spaans",
                            Title = "Spaans Conversatie",
                            UpdatedAt = new DateTime(2026, 1, 22, 10, 15, 21, 865, DateTimeKind.Utc).AddTicks(5933),
                            Visibility = 1
                        });
                });

            modelBuilder.Entity("noava.Models.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FaqKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FAQs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Noava is a modern platform that helps you manage your business efficiently with cutting-edge technology and user-friendly interfaces.",
                            FaqKey = "what_is_noava",
                            Question = "What is Noava?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Simply sign up, configure your preferences, and start using our intuitive dashboard to manage all your operations in one place.",
                            FaqKey = "how_does_it_work",
                            Question = "How does it work?"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "We offer flexible pricing plans starting from €9.99 per month. Visit our pricing page for detailed information about features included in each plan.",
                            FaqKey = "what_are_the_costs",
                            Question = "What are the costs?"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "Yes, you can cancel your subscription at any time without any penalties or hidden fees. Your data will remain accessible for 30 days after cancellation.",
                            FaqKey = "can_i_cancel_anytime",
                            Question = "Can I cancel anytime?"
                        },
                        new
                        {
                            Id = 5,
                            Answer = "Absolutely. We use industry-standard encryption, regular security audits, and comply with GDPR regulations to ensure your data is always protected.",
                            FaqKey = "is_my_data_secure",
                            Question = "Is my data secure?"
                        },
                        new
                        {
                            Id = 6,
                            Answer = "We offer 24/7 email support, live chat during business hours, and comprehensive documentation. Premium plans include priority support and dedicated account managers.",
                            FaqKey = "support_options_available",
                            Question = "What support options are available?"
                        },
                        new
                        {
                            Id = 7,
                            Answer = "Yes, Noava integrates with popular tools like Slack, Google Workspace, Microsoft 365, and many others through our API and pre-built connectors.",
                            FaqKey = "integration_with_other_tools",
                            Question = "Can I integrate with other tools?"
                        },
                        new
                        {
                            Id = 8,
                            Answer = "Yes, we offer a 14-day free trial with full access to all features. No credit card required to start your trial.",
                            FaqKey = "free_trial",
                            Question = "Do you offer a free trial?"
                        });
                });

            modelBuilder.Entity("noava.Models.User", b =>
                {
                    b.Property<string>("ClerkId")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClerkId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
