// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using noava.Data;

#nullable disable

namespace noava.Migrations
{
    [DbContext(typeof(NoavaDbContext))]
    partial class NoavaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("noava.Models.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("noava.Models.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FAQs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Noava is a modern platform that helps you manage your business efficiently with cutting-edge technology and user-friendly interfaces.",
                            Question = "What is Noava?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Simply sign up, configure your preferences, and start using our intuitive dashboard to manage all your operations in one place.",
                            Question = "How does it work?"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "We offer flexible pricing plans starting from €9.99 per month. Visit our pricing page for detailed information about features included in each plan.",
                            Question = "What are the costs?"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "Yes, you can cancel your subscription at any time without any penalties or hidden fees. Your data will remain accessible for 30 days after cancellation.",
                            Question = "Can I cancel anytime?"
                        },
                        new
                        {
                            Id = 5,
                            Answer = "Absolutely. We use industry-standard encryption, regular security audits, and comply with GDPR regulations to ensure your data is always protected.",
                            Question = "Is my data secure?"
                        },
                        new
                        {
                            Id = 6,
                            Answer = "We offer 24/7 email support, live chat during business hours, and comprehensive documentation. Premium plans include priority support and dedicated account managers.",
                            Question = "What support options are available?"
                        },
                        new
                        {
                            Id = 7,
                            Answer = "Yes, Noava integrates with popular tools like Slack, Google Workspace, Microsoft 365, and many others through our API and pre-built connectors.",
                            Question = "Can I integrate with other tools?"
                        },
                        new
                        {
                            Id = 8,
                            Answer = "Yes, we offer a 14-day free trial with full access to all features. No credit card required to start your trial.",
                            Question = "Do you offer a free trial?"
                        });
                });

            modelBuilder.Entity("noava.Models.User", b =>
                {
                    b.Property<string>("ClerkId")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClerkId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
